import { test, expect } from '@playwright/test';
import path from 'path';

const EVIDENCE_DIR = path.join(process.cwd(), '.sisyphus', 'evidence');

test('task-5 — Apply creates rescored revised panel (evidence screenshot)', async ({ page }) => {
  await page.route('/api/analyze', async (route) => {
    await route.fulfill({
      status: 200,
      json: {
        score: 0.85,
        text: 'This is a test essay. It has some AI generated content.',
        sentences: [
          { sentence: 'This is a test essay.', score: 0.1 },
          { sentence: 'It has some AI generated content.', score: 0.9 },
        ],
        highlights: [{ start: 22, end: 55, score: 0.9, label: 'high', sentenceIndex: 1 }],
        suggestions: [],
      },
    });
  });

  await page.route('**/api/suggestions', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        available: true,
        sentenceIndex: 1,
        rewrite: 'The document includes material generated by artificial intelligence.',
        explanation: 'More natural phrasing.',
      }),
    });
  });

  await page.route('**/api/analyze/revised', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        score: 0.25,
        text: 'This is a test essay. The document includes material generated by artificial intelligence.',
        sentences: [
          { sentence: 'This is a test essay.', score: 0.1 },
          { sentence: 'The document includes material generated by artificial intelligence.', score: 0.3 },
        ],
        highlights: [{ start: 22, end: 90, score: 0.3, label: 'low', sentenceIndex: 1 }],
        suggestions: [],
      }),
    });
  });

  await page.goto('/');

  const fileInput = page.getByTestId('file-input');
  await fileInput.setInputFiles({
    name: 'test.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    buffer: Buffer.from('mock file content'),
  });
  await page.getByTestId('submit-button').click();

  await expect(page.getByTestId('review-panel')).toBeVisible();
  await expect(page.getByTestId('revised-panel-section')).not.toBeVisible();

  await page.getByTestId('highlight-score').click();
  await expect(page.getByTestId('suggestion-popover')).toBeVisible();
  await page.getByTestId('apply-suggestion-btn').click();

  await expect(page.getByTestId('revised-panel-section')).toBeVisible();
  await expect(page.getByTestId('revised-review-panel')).toBeVisible();
  await expect(page.getByTestId('revised-overall-score')).toContainText('25.0% AI');

  await expect(page.getByTestId('review-panel')).toBeVisible();
  await expect(page.getByText('85.0% AI')).toBeVisible();

  await page.screenshot({ path: path.join(EVIDENCE_DIR, 'task-5-revised-panel.png'), fullPage: true });
});

test('task-5 — Revised-analysis request failure is handled cleanly (evidence screenshot)', async ({ page }) => {
  await page.route('/api/analyze', async (route) => {
    await route.fulfill({
      status: 200,
      json: {
        score: 0.85,
        text: 'This is a test essay. It has some AI generated content.',
        sentences: [
          { sentence: 'This is a test essay.', score: 0.1 },
          { sentence: 'It has some AI generated content.', score: 0.9 },
        ],
        highlights: [{ start: 22, end: 55, score: 0.9, label: 'high', sentenceIndex: 1 }],
        suggestions: [],
      },
    });
  });

  await page.route('**/api/suggestions', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        available: true,
        sentenceIndex: 1,
        rewrite: 'A rewritten version of the sentence.',
        explanation: 'Better phrasing.',
      }),
    });
  });

  await page.route('**/api/analyze/revised', async (route) => {
    await route.fulfill({
      status: 503,
      contentType: 'application/json',
      body: JSON.stringify({
        error: 'DETECTION_FAILED',
        message: 'Detection service is not configured.',
      }),
    });
  });

  await page.goto('/');

  const fileInput = page.getByTestId('file-input');
  await fileInput.setInputFiles({
    name: 'test.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    buffer: Buffer.from('mock file content'),
  });
  await page.getByTestId('submit-button').click();

  await expect(page.getByTestId('review-panel')).toBeVisible();

  await page.getByTestId('highlight-score').click();
  await expect(page.getByTestId('suggestion-popover')).toBeVisible();
  await page.getByTestId('apply-suggestion-btn').click();

  await expect(page.getByTestId('revised-panel-section')).toBeVisible();
  await expect(page.getByTestId('revised-error')).toBeVisible();
  await expect(page.getByTestId('review-panel')).toBeVisible();
  await expect(page.getByText('85.0% AI')).toBeVisible();

  await page.screenshot({ path: path.join(EVIDENCE_DIR, 'task-5-revised-panel-error.png'), fullPage: true });
});

test('task-7 — click-to-revert removes applied edit and rescores (evidence screenshot)', async ({ page }) => {
  await page.route('/api/analyze', async (route) => {
    await route.fulfill({
      status: 200,
      json: {
        score: 0.85,
        text: 'This is a test essay. It has some AI generated content.',
        sentences: [
          { sentence: 'This is a test essay.', score: 0.1 },
          { sentence: 'It has some AI generated content.', score: 0.9 },
        ],
        highlights: [{ start: 22, end: 55, score: 0.9, label: 'high', sentenceIndex: 1 }],
        suggestions: [],
      },
    });
  });

  await page.route('**/api/suggestions', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        available: true,
        sentenceIndex: 1,
        rewrite: 'The document includes material generated by artificial intelligence.',
        explanation: 'More natural phrasing.',
      }),
    });
  });

  await page.route('**/api/analyze/revised', async (route) => {
    const body = route.request().postDataJSON() as { text: string };
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        score: 0.25,
        text: body.text,
        sentences: [
          { sentence: 'This is a test essay.', score: 0.1 },
          { sentence: 'The document includes material generated by artificial intelligence.', score: 0.3 },
        ],
        highlights: [{ start: 22, end: 90, score: 0.3, label: 'low', sentenceIndex: 1 }],
        suggestions: [],
      }),
    });
  });

  await page.goto('/');

  const fileInput = page.getByTestId('file-input');
  await fileInput.setInputFiles({
    name: 'test.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    buffer: Buffer.from('mock file content'),
  });
  await page.getByTestId('submit-button').click();

  await page.getByTestId('highlight-score').click();
  await page.getByTestId('apply-suggestion-btn').click();

  await expect(page.getByTestId('revised-panel-section')).toBeVisible();
  await expect(page.getByTestId('revised-overall-score')).toContainText('25.0% AI');

  const revisedHighlight = page.getByTestId('revised-highlight-score');
  await revisedHighlight.click();

  await expect(page.getByTestId('revised-panel-section')).not.toBeVisible();
  await expect(page.getByTestId('review-panel')).toBeVisible();

  await page.screenshot({ path: path.join(EVIDENCE_DIR, 'task-7-undo-flow.png'), fullPage: true });
});

test('task-7 — undoing the last applied edit clears revised preview state safely (evidence screenshot)', async ({ page }) => {
  await page.route('/api/analyze', async (route) => {
    await route.fulfill({
      status: 200,
      json: {
        score: 0.85,
        text: 'This is a test essay. It has some AI generated content.',
        sentences: [
          { sentence: 'This is a test essay.', score: 0.1 },
          { sentence: 'It has some AI generated content.', score: 0.9 },
        ],
        highlights: [{ start: 22, end: 55, score: 0.9, label: 'high', sentenceIndex: 1 }],
        suggestions: [],
      },
    });
  });

  await page.route('**/api/suggestions', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        available: true,
        sentenceIndex: 1,
        rewrite: 'The document includes material generated by artificial intelligence.',
        explanation: 'More natural phrasing.',
      }),
    });
  });

  await page.route('**/api/analyze/revised', async (route) => {
    const body = route.request().postDataJSON() as { text: string };
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        score: 0.25,
        text: body.text,
        sentences: [
          { sentence: 'This is a test essay.', score: 0.1 },
          { sentence: 'The document includes material generated by artificial intelligence.', score: 0.3 },
        ],
        highlights: [{ start: 22, end: 90, score: 0.3, label: 'low', sentenceIndex: 1 }],
        suggestions: [],
      }),
    });
  });

  await page.goto('/');

  const fileInput = page.getByTestId('file-input');
  await fileInput.setInputFiles({
    name: 'test.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    buffer: Buffer.from('mock file content'),
  });
  await page.getByTestId('submit-button').click();

  await page.getByTestId('highlight-score').click();
  await page.getByTestId('apply-suggestion-btn').click();

  await expect(page.getByTestId('revised-panel-section')).toBeVisible();

  const revisedHighlight = page.getByTestId('revised-highlight-score');
  await revisedHighlight.click();

  await expect(page.getByTestId('revised-panel-section')).not.toBeVisible();

  await page.screenshot({ path: path.join(EVIDENCE_DIR, 'task-7-undo-flow-error.png'), fullPage: true });
});
