import { expect, test } from '@playwright/test';
import path from 'path';

const EVIDENCE = path.resolve(__dirname, '../.sisyphus/evidence');

test('medium-risk label click opens suggestion details', async ({ page }) => {
  await page.route('**/api/analyze', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        score: 0.5,
        text: 'This is a safe sentence. This one has medium AI risk.',
        sentences: [
          { sentence: 'This is a safe sentence.', score: 0.1 },
          { sentence: 'This one has medium AI risk.', score: 0.55 },
        ],
        highlights: [
          { start: 25, end: 52, score: 0.55, label: 'medium', sentenceIndex: 1 },
        ],
        suggestions: [],
      }),
    });
  });

  await page.route('**/api/suggestions', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        available: true,
        sentenceIndex: 1,
        rewrite: 'This sentence carries a moderate level of AI-like phrasing.',
        explanation: 'Reworded to reduce formulaic structure.',
      }),
    });
  });

  await page.goto('/');
  await page.getByTestId('file-input').setInputFiles({
    name: 'essay.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    buffer: Buffer.from('mock content'),
  });
  await page.getByTestId('submit-button').click();

  await expect(page.getByTestId('review-panel')).toBeVisible();

  const highlights = page.getByTestId('highlight-score');
  await expect(highlights).toHaveCount(1);
  await expect(highlights.first()).toContainText('Medium Risk');

  await highlights.first().click();
  const popover = page.getByTestId('suggestion-popover');
  await expect(popover).toBeVisible();
  await expect(page.getByText('This sentence carries a moderate level of AI-like phrasing.')).toBeVisible();
  await expect(page.getByTestId('apply-suggestion-btn-0')).toBeVisible();
});

test('full dual-pane happy path: upload → click label → apply → revised panel → revert', async ({ page }) => {
  await page.route('**/api/analyze', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        score: 0.85,
        text: 'This is a test essay. It has some AI generated content.',
        sentences: [
          { sentence: 'This is a test essay.', score: 0.1 },
          { sentence: 'It has some AI generated content.', score: 0.9 },
        ],
        highlights: [
          { start: 22, end: 55, score: 0.9, label: 'high', sentenceIndex: 1 },
        ],
        suggestions: [],
      }),
    });
  });

  await page.route('**/api/suggestions', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        available: true,
        sentenceIndex: 1,
        rewrite: 'The document includes material generated by artificial intelligence.',
        explanation: 'More natural phrasing reduces AI-like risk.',
      }),
    });
  });

  const revisedCallBodies: string[] = [];
  await page.route('**/api/analyze/revised', async (route) => {
    const body = route.request().postDataJSON() as { text: string };
    revisedCallBodies.push(body.text);
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        score: 0.25,
        text: body.text,
        sentences: [
          { sentence: 'This is a test essay.', score: 0.1 },
          {
            sentence: 'The document includes material generated by artificial intelligence.',
            score: 0.3,
          },
        ],
        highlights: [
          { start: 22, end: 90, score: 0.3, label: 'low', sentenceIndex: 1 },
        ],
        suggestions: [],
      }),
    });
  });

  await page.goto('/');

  await page.getByTestId('file-input').setInputFiles({
    name: 'test.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    buffer: Buffer.from('mock file content'),
  });
  await page.getByTestId('submit-button').click();

  await expect(page.getByTestId('review-panel')).toBeVisible();
  await expect(page.getByTestId('revised-panel-section')).not.toBeVisible();
  await expect(page.getByText('85.0% AI')).toBeVisible();

  await page.getByTestId('highlight-score').click();
  await expect(page.getByTestId('suggestion-popover')).toBeVisible();

  await page.screenshot({
    path: `${EVIDENCE}/task-8-dual-pane-regression-before-apply.png`,
    fullPage: true,
  });

  await page.getByTestId('apply-suggestion-btn-0').click();

  await expect(page.getByTestId('revised-panel-section')).toBeVisible();
  await expect(page.getByTestId('revised-review-panel')).toBeVisible();
  await expect(page.getByTestId('revised-overall-score')).toContainText('25.0% AI');
  await expect(page.getByTestId('review-panel')).toBeVisible();
  await expect(page.getByText('85.0% AI')).toBeVisible();

  await page.screenshot({
    path: `${EVIDENCE}/task-8-dual-pane-regression.png`,
    fullPage: true,
  });

  const revisedHighlight = page.getByTestId('revised-highlight-score');
  await expect(revisedHighlight).toBeVisible();
  await revisedHighlight.click();

  await expect(page.getByTestId('revised-panel-section')).not.toBeVisible();
  expect(revisedCallBodies.length).toBe(1);

  await expect(page.getByTestId('review-panel')).toBeVisible();
  await expect(page.getByText('85.0% AI')).toBeVisible();
});
